"""
api/main.py
-----------
FastAPI REST backend for the Autonomous AI Research Agent.

Endpoints:
  POST /research          — Start a research job (async, returns job_id)
  GET  /research/{job_id} — Poll job status and retrieve results
  GET  /health            — Health check

Jobs run in a background thread pool to avoid blocking the event loop
during long-running LLM and scraping operations.
"""

from __future__ import annotations

import asyncio
import uuid
from datetime import datetime
from enum import Enum
from typing import Any, Optional

from fastapi import FastAPI, HTTPException, BackgroundTasks
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

from core.workflow import run_research_pipeline
from utils.logger import get_logger

logger = get_logger(__name__)

# ── FastAPI App ───────────────────────────────────────────────────────────────

app = FastAPI(
    title="Autonomous AI Research Agent",
    description=(
        "Submit a research query and receive a structured, multi-source "
        "research report generated by a LangGraph agent pipeline."
    ),
    version="1.0.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


# ── In-memory Job Store ───────────────────────────────────────────────────────
# For production, replace with Redis or a database.

class JobStatus(str, Enum):
    PENDING = "pending"
    RUNNING = "running"
    COMPLETE = "complete"
    FAILED = "failed"


_JOB_STORE: dict[str, dict[str, Any]] = {}


# ── Request / Response Schemas ────────────────────────────────────────────────

class ResearchRequest(BaseModel):
    query: str = Field(
        ...,
        min_length=5,
        max_length=500,
        example="Latest AI tools for healthcare diagnosis",
    )


class ResearchJobResponse(BaseModel):
    job_id: str
    status: JobStatus
    message: str


class ResearchResultResponse(BaseModel):
    job_id: str
    status: JobStatus
    query: Optional[str] = None
    report_markdown: Optional[str] = None
    report_metadata: Optional[dict] = None
    google_doc_url: Optional[str] = None
    google_sheet_url: Optional[str] = None
    local_file_path: Optional[str] = None
    agent_logs: Optional[list[str]] = None
    errors: Optional[list[str]] = None
    created_at: Optional[str] = None
    completed_at: Optional[str] = None


# ── Background Job Runner ─────────────────────────────────────────────────────

async def _run_job(job_id: str, query: str) -> None:
    """Execute the research pipeline for *query* and update *job_id* in the store."""
    _JOB_STORE[job_id]["status"] = JobStatus.RUNNING
    try:
        result = await run_research_pipeline(query)
        _JOB_STORE[job_id].update(
            {
                "status": JobStatus.COMPLETE,
                "result": result,
                "completed_at": datetime.utcnow().isoformat() + "Z",
            }
        )
        logger.info("job_complete", job_id=job_id)
    except Exception as exc:
        logger.error("job_failed", job_id=job_id, error=str(exc))
        _JOB_STORE[job_id].update(
            {
                "status": JobStatus.FAILED,
                "error": str(exc),
                "completed_at": datetime.utcnow().isoformat() + "Z",
            }
        )


# ── Routes ────────────────────────────────────────────────────────────────────

@app.get("/health", tags=["System"])
async def health_check() -> dict[str, str]:
    """Returns service health status."""
    return {"status": "healthy", "service": "Autonomous AI Research Agent"}


@app.post("/research", response_model=ResearchJobResponse, status_code=202, tags=["Research"])
async def start_research(
    request: ResearchRequest,
    background_tasks: BackgroundTasks,
) -> ResearchJobResponse:
    """
    Submit a research query.

    The job runs asynchronously. Poll `GET /research/{job_id}` for results.
    """
    job_id = str(uuid.uuid4())
    created_at = datetime.utcnow().isoformat() + "Z"

    _JOB_STORE[job_id] = {
        "job_id": job_id,
        "query": request.query,
        "status": JobStatus.PENDING,
        "created_at": created_at,
        "result": None,
        "error": None,
    }

    background_tasks.add_task(_run_job, job_id, request.query)

    logger.info("job_created", job_id=job_id, query=request.query)

    return ResearchJobResponse(
        job_id=job_id,
        status=JobStatus.PENDING,
        message=f"Research job created. Poll GET /research/{job_id} for results.",
    )


@app.get("/research/{job_id}", response_model=ResearchResultResponse, tags=["Research"])
async def get_research_result(job_id: str) -> ResearchResultResponse:
    """
    Retrieve the status and results of a research job.

    - **pending** / **running**: job is still in progress.
    - **complete**: `report_markdown` and all output fields are populated.
    - **failed**: `errors` field contains the failure reason.
    """
    job = _JOB_STORE.get(job_id)
    if not job:
        raise HTTPException(status_code=404, detail=f"Job '{job_id}' not found.")

    status = job["status"]
    result = job.get("result") or {}

    return ResearchResultResponse(
        job_id=job_id,
        status=status,
        query=job.get("query"),
        report_markdown=result.get("report_markdown"),
        report_metadata=result.get("report_metadata"),
        google_doc_url=result.get("google_doc_url"),
        google_sheet_url=result.get("google_sheet_url"),
        local_file_path=result.get("local_file_path"),
        agent_logs=result.get("agent_logs", []),
        errors=result.get("errors") or ([job["error"]] if job.get("error") else []),
        created_at=job.get("created_at"),
        completed_at=job.get("completed_at"),
    )


@app.get("/research", tags=["Research"])
async def list_jobs() -> list[dict[str, Any]]:
    """List all research jobs with their current status."""
    return [
        {
            "job_id": j["job_id"],
            "query": j["query"],
            "status": j["status"],
            "created_at": j.get("created_at"),
            "completed_at": j.get("completed_at"),
        }
        for j in _JOB_STORE.values()
    ]


# ── Entry Point ───────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import uvicorn
    from core.config import settings

    uvicorn.run(
        "api.main:app",
        host=settings.API_HOST,
        port=settings.API_PORT,
        reload=False,
    )
